<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQzPVHx3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQzPVHx3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQzPVHx3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQzPVHx3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQzPVHx3\App_KernelDevDebugContainer([
    'container.build_hash' => 'QzPVHx3',
    'container.build_id' => '2263d382',
    'container.build_time' => 1695307276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQzPVHx3');
