<?php

namespace ContainerR1Hll3A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WgckvdZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wgckvdZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wgckvdZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PDF' => ['privates', 'App\\PDF', 'getPDFService', true],
        ], [
            'PDF' => 'App\\PDF',
        ]);
    }
}
