<?php

namespace ContainerR1Hll3A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrincipaleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PrincipaleController' shared autowired service.
     *
     * @return \App\Controller\PrincipaleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PrincipaleController.php';

        $container->services['App\\Controller\\PrincipaleController'] = $instance = new \App\Controller\PrincipaleController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\PrincipaleController', $container));

        return $instance;
    }
}
