<?php

namespace ContainerOOGFSeZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGYdr5gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pGYdr5g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pGYdr5g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\InscriptionController::showForm' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Controller\\PrincipaleController::showForm' => ['privates', '.service_locator.wgckvdZ', 'get_ServiceLocator_WgckvdZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\InscriptionController:showForm' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Controller\\PrincipaleController:showForm' => ['privates', '.service_locator.wgckvdZ', 'get_ServiceLocator_WgckvdZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\InscriptionController::showForm' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\PrincipaleController::showForm' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\InscriptionController:showForm' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\PrincipaleController:showForm' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
